name: Tests

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        # Tests a range of Ruby to ensure the gem works.
        # Keeps 2.7 for a while but support EOL Ruby for a year in general
        # Read more about Ruby EOL date on https://endoflife.date/ruby
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - head
        # test distributions up to 4 years
        runner:
          - ubuntu-latest
          - ubuntu-20.04
      fail-fast: false # allow contributors understand failure builds

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # cppjieba requires a vendor library in a submodule

      - name: Set up Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
